repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

# isort
- repo: https://github.com/PyCQA/isort
  rev: 5.7.0
  hooks:
  - id: isort
    args:
    - .

# black
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    args:
    - --line-length=88
    - --include='\.pyi?$'
    # these folders wont be formatted by black
    - --exclude="""\.git |
        \.__pycache__|
        \.hg|
        \.mypy_cache|
        \.tox|
        \.venv|
        _build|
        buck-out|
        build|
        dist"""
    language_version: python3.8

# flake8
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
