version: '3.7'
services:
    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow

    spark:
        build:
            context: spark
            dockerfile: Dockerfile
        ports:
            - 8000:8080
        volumes:
            - ./credentials:/credentials
        env_file:
            - .env
        command: start-master.sh

    spark-worker:
        build:
            context: spark
            dockerfile: Dockerfile
        depends_on:
            - spark
        env_file:
            - .env
        environment:
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=6G
            - SPARK_WORKER_CORES=6
        volumes:
            - ./credentials:/credentials
        command: start-slave.sh $${SPARK_MASTER_URL}

    airflow:
        build:
            context: airflow
            dockerfile: Dockerfile
        depends_on:
            - airflow_postgres
        env_file:
            - .env
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT='google-cloud-platform://?extra__google_cloud_platform__key_path=/credentials/gcloud_credentials.json'
            - AIRFLOW_CONN_SPARK_DEFAULT=spark://admin:admin@spark%3A%2F%2Fspark:7077
        volumes:
            - ./credentials:/credentials
            - ./airflow/dags:/opt/airflow/dags
        ports:
            - 8080:8080
        command: >
            bash -c "
                airflow db upgrade;
                airflow users create \
                    --role Admin \
                    --username admin \
                    --password admin \
                    --firstname Airflow \
                    --lastname Admin \
                    --email welberthime@gmail.com;
                rm $${AIRFLOW_HOME}/*.pid $${AIRFLOW_HOME}/*.err;
                airflow webserver -D & airflow scheduler"
