version: '3.7'
services:
    spark:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8080
            - 7077:7077
        environment:
            - GCS_BUCKET=$GCS_BUCKET
        command: start-master.sh

    spark-worker:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - spark
        environment:
            - GCS_BUCKET=$GCS_BUCKET
            - SPARK_MASTER_URL=spark:7077
            - SPARK_WORKER_MEMORY=6G
            - SPARK_WORKER_CORES=6
        command: start-slave.sh spark:7077
