version: '3.7'
services:
    spark:
        build:
            context: .
            dockerfile: Dockerfile
        command: start-master.sh
        environment:
            - GCS_BUCKET=$GCS_BUCKET
        ports:
            - 8000:8080
    spark-worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: start-slave.sh spark:7077
        depends_on:
            - spark
        environment:
            - GCS_BUCKET=$GCS_BUCKET
            - SPARK_MASTER_URL=spark:7077
            - SPARK_WORKER_MEMORY=6G
            - SPARK_WORKER_CORES=6

networks:
    default:
        external: true
        name: airport_streaming
