version: '3.7'
services:
    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow

    airflow:
        build:
            context: airflow
            dockerfile: Dockerfile
            args:
                - USER_ID=$USER_ID
                - GROUP_ID=$GROUP_ID
        depends_on:
            - postgres
        environment:
            - AIRFLOW_CONN_SPARK_DEFAULT=spark://admin:admin@localhost:7077
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - BQ_DATASET=$BQ_DATASET
            - BQ_VIEWS=$BQ_VIEWS
            - GCS_BUCKET=$GCS_BUCKET
            - GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT
        volumes:
            - ./airflow/dags:/opt/airflow/dags
        ports:
            - 8080:8080
